### ISSUE TITLE
Content is missing when using as library

### ISSUE THREAD

**Issue by buehler** [angelobreuer/localtunnel-client#8]
Hey @angelobreuer 

This is a nice project to be used as dotnet library. Sadly, it does cut off content :-(

I'm trying to use it for my Kubernetes Operator SDK. The tunnel gets created and does proxy correctly to the localhost application. But the content is missing around 3000 characters. It is a json payload.

I create the tunnel via: https://github.com/buehler/dotnet-operator-sdk/blob/feat/localtunnel-integration/src/KubeOps/Operator/Webhooks/WebhookLocalTunnel.cs#L52-L69

And then parsing the request: https://github.com/buehler/dotnet-operator-sdk/blob/feat/localtunnel-integration/src/KubeOps/Operator/Webhooks/IAdmissionWebhook%7BTEntity%2C%20TResult%7D.cs#L119-L121

Now, when using ngrok, the content that I receive in the example is around 9000 characters. When using localtunnel (as library) I receive 6875 characters worth of json. Since there is a bunch of data missing, the conversion throws and exception.

Do you have any idea what could cause this?

Regards
Chris

**Comment by buehler** [comment]
Appendix: it seems that the bytes transferred do not match 🤷🏾

**Comment by buehler** [comment]
Just made a test with your CLI. When using "passthrough" it seems to work.

**Comment by buehler** [comment]
It does work when the request process is removed. Maybe this should be the default? wdyt?

**Comment by angelobreuer** [comment]
Hello @buehler,

thank you for your issue!

The reason that the request processing is on by default is that localtunnel should act as an HTTP(S) proxy. The passthrough mode does not process the request headers. Some websites have virtual sites, or they do not even respond to a host header different from the target website. E.g., the browser sends an HTTP(S) request with `Host: mytunnel.loca.lt` to the target server. The server does not know how to process the request as the server is not supposed to serve the website for `mytunnel.loca.lt`. So localtunnel-client parses the request and rewrites the host header in order to avoid the issue.

If you have an HTTP API that does not care about the host header value, you can safely enable the passthrough mode. Also, the request processing mode adds some overhead to the actual request flow. 

During the investigation I've found a bug in the dashboard, that results in showing a wrong transfer size (the out and in values are always the same), which may be related to the statement above.

I've tried downloading using various files with various sizes (100 KiB, 5 MiB, 100 MiB, 1 GiB, 5 GiB) and both hash and size were correct in passthrough and request processing mode. But suddenly, I have been unable to reproduce the issue mentioned above.

I could imagine that the issue could be in relation to using HTTP compression, HTTP chunking, ... Is the JSON cut straight off, or are only parts in the JSON missing? I think there could be an issue when using the request processing mode, that the content length is written incorrectly, which could cause that the JSON could be cut straight off.

I will try out some other scenarios where those problems could happen later this day and tell you, my results.

Thank you!

**Comment by buehler** [comment]
Hey @angelobreuer 

Thanks for the detailed Answer! I guess I get it. The thing is, I've been working with ngrok for a while, and they do not parse HTTP headers as I'm aware of. So when using localtunnel to proxy a connection to my ASP.Net application, the HTTP headers mustn't be parsed, because ASP will do so.

This makes sense as it is now. One thing that I'd suggest: Investigate the default ASP.Net request parser, maybe you could use it instead of a custom made one such that you can use the default ecosystem of ASP.Net. Then you don't have to code everything by yourself ;-)
